var Speeches = {
	'hole_sign': { text: 'It reads: Watch out for danger! This hole is not safe to jump into.' },
	'phone': { text: 'There’s still a noise when I pick it up.' },
	'tomatoes': { text: 'Mmm, what juicy little apples... or are they tomatoes?', portrait: 'Enticed' },
	'shade_tree': { text: 'This looks like a good spot for a nap.' },
	'pillar': { text: 'This looks dangerous...', portrait: 'Displeased' },
	'jerk': { text: 'Sneaky jerk', portrait: 'Mad' },
	'mushrooms': { text: 'These mushrooms don’t look safe to eat... I better not', portrait: 'Enticed' },
	'wet_clay': { text: 'Hope I don\'t fall!' },
	'dew': { text: 'These flowers are covered in dew' },
	'draft': { text: 'I can’t see anything out the window, but I can feel a breeze coming through' },
	'dripping': { text: 'Eee, the water is dripping on me', portrait: 'Mischeif' },
	'fresh': { text: 'The air smells fresh in this room', portrait: 'Peaceful' },
	'extract': { text: 'It looks like they were extracting something here' },
	'spores': { text: 'These spores are making me dizzy', portrait: 'Dazed' },
	'delicate_flower': { text: 'This flower looks delicate... I wonder how long it’s been growing' },
	'door_info': { text: 'It won\'t open from this side.' },
	'strange_wall': { text: 'This wall looks strange...' },
	'weak_floor': { text: 'The floor looks pretty messed up.', portrait: 'Displeased' },
	'more_flowers': { text: 'More of these flowers. The scent is wonderful.', portrait: 'Peaceful' },
	'how_standing': { text: 'How is this thing even standing?' },
	'down_there': { text: 'Hmm I wonder what\'s down there.' },
	'jump_in': { text: 'Should I jump in? It looks pretty scary, I might get blown around' },
	'tanks': { text: 'These tanks smells yucky' },
	'yum_apple': { text: 'That apple looks yummy', portrait: 'Enticed' },
	'yuck_ground': { text: 'Yuck, the ground is all soggy. It\'s getting my socks wet', portrait: 'Displeased' },
	'secret_garden': { text: 'A secret little garden. I wonder who made it.' },
	'ohh': { text: 'Oh... I thought there would be something up here.', portrait: 'Displeased' },
	'cant_see': { text: 'I can barely see past all these vines.. but I can feel something up ahead' },
	'prickly_stuff': { text: 'What is this prickly stuff any way? It\'s really annoying.', portrait: 'Mad' },
	'ceiling': { text: 'I can barely see the ceiling, it\'s so high. I wonder how this is all still standing.' },
	'up_there': { text: 'Hmm I wonder how I can get up there.' },
	'whew': { text: 'Whew, that was tricky.' },
	'look_down': { text: 'Don\'t look down... Don\'t look down...', portrait: 'Dazed' },
	'fire': { text: 'The fire is warm. Maybe I can dry my socks off a little bit' },
	'dont_eat': { text: 'No matter how tasty it looks, don\'t eat that mushroom...', portrait: 'Enticed' },
	'nibble': { text: 'Just a little nibble couldn\'t hurt... could it?', portrait: 'Mischeif' },
	'cold': { text: 'This water is so cold, it\'s making my knees shake', portrait: 'Displeased' },
	'ellipses': { text: '...', portrait: 'Peaceful' },
	'anyone_home': { text: 'Is anyone home? I better not peep', portrait: 'Mischeif' },
	'football': { text: 'Football is fun! I wonder if maybe I could score a goal' },
	'sorry_plant': { text: 'Sorry plant' },
	'maybe_if': { text: 'Maybe if I just...' },
	'hidden_goodies': { text: 'He he, hidden goodies!', portrait: 'Silly'},
	'flower_helper': { text: 'You\'re a lucky little flower, getting all this light through the window.' },
	'go_away': { text: 'Go away you brute!', portrait: 'Mad' },

};